/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

type CommitStats struct {
	ID        string `json:"id,omitempty"`
	Additions int   `json:"additions,omitempty"`
	Deletions int   `json:"deletions,omitempty"`
	Total     int   `json:"total,omitempty"`
}
