/*
 * 码云 Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 5.3.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package gitee

// tag的Commit信息
type TagCommit struct {
	Sha  string `json:"sha,omitempty"`
	Date string `json:"date,omitempty"`
}
